In [1]:
import numpy as np
import pandas as pd
import datetime

In [2]:
start_time = datetime.datetime.now()

In [3]:
train = pd.read_csv(r'E:\Santander Recommendation\train_ver2.csv')

C:\Users\liamc\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
product_cols = ['ind_ahor_fin_ult1','ind_aval_fin_ult1','ind_cco_fin_ult1','ind_cder_fin_ult1',
                'ind_cno_fin_ult1','ind_ctju_fin_ult1','ind_ctma_fin_ult1','ind_ctop_fin_ult1',
                'ind_ctpp_fin_ult1','ind_deco_fin_ult1','ind_dela_fin_ult1','ind_deme_fin_ult1',
                'ind_ecue_fin_ult1','ind_fond_fin_ult1','ind_hip_fin_ult1','ind_nom_pens_ult1',
                'ind_nomina_ult1','ind_plan_fin_ult1','ind_pres_fin_ult1','ind_reca_fin_ult1',
               'ind_recibo_ult1','ind_tjcr_fin_ult1','ind_valo_fin_ult1','ind_viv_fin_ult1']

In [5]:
#product_cols = ['ind_cco_fin_ult1',
 #               'ind_cno_fin_ult1','ind_ctju_fin_ult1','ind_ctma_fin_ult1','ind_ctop_fin_ult1',
  #              'ind_ctpp_fin_ult1','ind_deco_fin_ult1','ind_dela_fin_ult1','ind_deme_fin_ult1',
   #             'ind_ecue_fin_ult1','ind_fond_fin_ult1','ind_nom_pens_ult1',
    #            'ind_nomina_ult1','ind_plan_fin_ult1','ind_pres_fin_ult1','ind_reca_fin_ult1',
     #           'ind_recibo_ult1','ind_tjcr_fin_ult1','ind_valo_fin_ult1']
#excluded 5 least frequent

In [6]:
dates = train.fecha_dato.unique()

In [7]:
dates

array(['2015-01-28', '2015-02-28', '2015-03-28', '2015-04-28',
       '2015-05-28', '2015-06-28', '2015-07-28', '2015-08-28',
       '2015-09-28', '2015-10-28', '2015-11-28', '2015-12-28',
       '2016-01-28', '2016-02-28', '2016-03-28', '2016-04-28',
       '2016-05-28'], dtype=object)

In [8]:
#months=[]
#for date in dates:
 #   months.append(train.loc[train['fecha_dato']==str(date)])
  #      #months[i] = train.loc[train['fecha_dato']==str(date)]
#len(months)       

In [9]:
m1 = train.loc[train['fecha_dato']==dates[0], product_cols+['ncodpers']]
m2 = train.loc[train['fecha_dato']==dates[1], product_cols+['ncodpers']]
m3 = train.loc[train['fecha_dato']==dates[2], product_cols+['ncodpers']]
m4 = train.loc[train['fecha_dato']==dates[3], product_cols+['ncodpers']]
m5 = train.loc[train['fecha_dato']==dates[4], product_cols+['ncodpers']]
m6 = train.loc[train['fecha_dato']==dates[5], product_cols+['ncodpers']]
m7 = train.loc[train['fecha_dato']==dates[6], product_cols+['ncodpers']]
m8 = train.loc[train['fecha_dato']==dates[7], product_cols+['ncodpers']]
m9 = train.loc[train['fecha_dato']==dates[8], product_cols+['ncodpers']]
m10 = train.loc[train['fecha_dato']==dates[9], product_cols+['ncodpers']]
m11 = train.loc[train['fecha_dato']==dates[10], product_cols+['ncodpers']]
m12 = train.loc[train['fecha_dato']==dates[11], product_cols+['ncodpers']]
m13 = train.loc[train['fecha_dato']==dates[12], product_cols+['ncodpers']]
m14 = train.loc[train['fecha_dato']==dates[13], product_cols+['ncodpers']]
m15 = train.loc[train['fecha_dato']==dates[14], product_cols+['ncodpers']]
m16 = train.loc[train['fecha_dato']==dates[15], product_cols+['ncodpers']]
m17 = train.loc[train['fecha_dato']==dates[16], product_cols+['ncodpers']]

In [10]:
final_month = train[train.fecha_dato == '2016-05-28']

In [11]:
train = []

In [12]:
from lightfm.data import Dataset

C:\Users\liamc\Anaconda3\lib\site-packages\lightfm\_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '


In [13]:
dataset = Dataset()

#### I may need to define function for the sequential partial fitting of each model to the model

In [14]:
dataset.fit_partial(m1['ncodpers'],product_cols)

In [15]:
dataset.fit_partial(m2['ncodpers'],product_cols)

In [16]:
dataset.fit_partial(m3['ncodpers'],product_cols)
dataset.fit_partial(m4['ncodpers'],product_cols)
dataset.fit_partial(m5['ncodpers'],product_cols)
dataset.fit_partial(m6['ncodpers'],product_cols)
dataset.fit_partial(m7['ncodpers'],product_cols)
dataset.fit_partial(m8['ncodpers'],product_cols)
dataset.fit_partial(m9['ncodpers'],product_cols)
dataset.fit_partial(m10['ncodpers'],product_cols)
dataset.fit_partial(m11['ncodpers'],product_cols)
dataset.fit_partial(m12['ncodpers'],product_cols)
dataset.fit_partial(m13['ncodpers'],product_cols)
dataset.fit_partial(m14['ncodpers'],product_cols)
dataset.fit_partial(m15['ncodpers'],product_cols)
dataset.fit_partial(m16['ncodpers'],product_cols)
dataset.fit_partial(m17['ncodpers'],product_cols)

In [17]:
num_users, num_items = dataset.interactions_shape()
print('Num users: {}, num_items {}.'.format(num_users, num_items))

Num users: 956645, num_items 24.


In [18]:
from lightfm import LightFM

model = LightFM(no_components=20,learning_schedule='adadelta',loss='warp')

#### Probably better add the interactions for each month using a loop

In [19]:
months = [m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17]
month_weights= [.5,.5,.5,.5,1,3,.5,.5,.5,.5,1,1,1,1,1,1,2]

In [20]:
weight=0
for m in months:
    labels = m.set_index("ncodpers")
    stacked_labels = labels.stack()
    filtered_labels = stacked_labels.reset_index()
    filtered_labels['weights'] = month_weights[weight]
    filtered_labels.columns = ["ncodpers", "product", "interaction",'weights']
    interactionsdf = filtered_labels.loc[filtered_labels['interaction']==1]
    (interactions, weights) = dataset.build_interactions((interactionsdf.iloc[x,0], interactionsdf.iloc[x,1], interactionsdf.iloc[x,2])
                                                     for x in range(len(interactionsdf)))
    print(repr(interactions))
    model.fit_partial(interactions,epochs=7)
    weight += 1
    
    

<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1109367 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1112733 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1118829 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1124795 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1119858 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1132501 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1147960 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1151798 stored elements in COOrdinate format>
<956645x24 sparse matrix of type '<class 'numpy.int32'>'
	with 1173705 stored elements in COOrdinate format>
<956645x24 sparse m

In [21]:
test = pd.read_csv(r'E:\Santander Recommendation\test_ver2.csv')

C:\Users\liamc\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [22]:
#test.loc[test.renta == '         NA',"renta"] = 0
#test.renta = test.renta.astype(float)
#test.loc[test.renta == 0, 'renta'] = test[test.renta > 0].groupby('nomprov').renta.transform('median')
#test.loc[test.renta.isnull(), "renta"] = test.groupby('nomprov').renta.transform('median')
#test.renta = test.renta.fillna(test.renta.median())
#test['rentaGroup'] = test.renta.astype(float) // 20000
#test.loc[test.renta >= 400000, "rentaGroup"] = 20
#test.loc[test.renta >= 1000000, "rentaGroup"] = 21
#incomelevel = test.rentaGroup.values
#d = {'users':users,'incomelevel':incomelevel}
#features = pd.DataFrame(d)
#dataset.fit_partial(users=users,user_features=incomelevels)
#user_features = dataset.build_user_features((features.iloc[x,0], [features.iloc[x,1]])
 #                                                    for x in range(len(features)))
#features.head()
#print(repr(user_features))
#model = LightFM(loss='bpr')
#model.fit(interactions,user_features=user_features,epochs=10,verbose=True)

In [23]:
users = test.ncodpers.values

In [24]:
users

array([  15889, 1170544, 1170545, ...,  660240,  660243,  660248],
      dtype=int64)

In [25]:
n_users, n_items = dataset.interactions_shape()

In [26]:
item_ids = np.arange(n_items)
model.predict(0,item_ids)

array([-1.26108146, -1.89072335,  5.86718416, -0.66844809,  1.58206868,
       -1.68874311,  1.68639874,  0.40130308, -0.15004243, -1.8489728 ,
        0.15680848, -1.92260516,  2.26568317,  0.01055612, -1.29948819,
        2.32537699,  2.6578114 ,  0.81399935, -0.87748647,  1.37966883,
        4.61672735,  1.95125794,  0.85652059, -1.53693748])

In [27]:
dataset.mapping()[1][1170544]

235546

In [28]:
preds = []
item_ids = np.arange(n_items)
for user_id in users:
    emb_id = dataset.mapping()[1][user_id]
    scores = model.predict(emb_id,item_ids)
    preds.append(scores)
    scores = []

In [29]:
preds =np.array([np.array(predi) for predi in preds])

In [30]:
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)

In [31]:
preds[0]

array([22,  8,  2, 21,  5, 15,  6, 16, 13, 20, 18, 10, 17,  3, 12,  4,  0,
        9,  1, 23, 11, 14, 19,  7], dtype=int64)

In [32]:
m1 = []
m2 = []
m3 = []
m4 = []
m5 = []
m6 = []
m7 = []
m8 = []
m9 = []
m10 = []
m11 = []
m12 = []
m13 = []
m14 = []
m15 = []
m16 = []
m17 = []

In [33]:
print("Step 1/11")
#Get the target columns
labels_final_month = final_month[product_cols]
print("Step 2/11")
#Add ncodpers to the dataframe
labels_final_month['ncodpers'] = final_month.ncodpers
print("Step 3/11")
labels_final_month = labels_final_month.set_index("ncodpers")
print("Step 4/11")
stacked_labels_final_month = labels_final_month.stack()
print("Step 5/11")
filtered_labels_final_month = stacked_labels_final_month.reset_index()
print("Step 6/11")
filtered_labels_final_month.columns = ["ncodpers", "product", "owned"]
print("Step 7/11")
#Only select the rows where there is a new product.
filtered_labels_final_month = filtered_labels_final_month[filtered_labels_final_month["owned"] == 1]
print("Step 8/11")
#Merge with the training features.
print("Step 9/11")
final_month = filtered_labels_final_month.drop_duplicates(keep='last')
print("Step 10/11")
labels_final_month_final = final_month['product']

Step 1/11
Step 2/11
Step 3/11


C:\Users\liamc\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


Step 4/11
Step 5/11
Step 6/11
Step 7/11
Step 8/11
Step 9/11
Step 10/11


In [34]:
final_month['product_#'] = labels_final_month_final.astype('category').cat.codes

In [35]:
final_month.head()

ncodpers            product  owned  product_#
26    657788   ind_cco_fin_ult1    1.0          2
50    657795   ind_cco_fin_ult1    1.0          2
76    657790   ind_cno_fin_ult1    1.0          4
84    657790  ind_ecue_fin_ult1    1.0         12
87    657790  ind_nom_pens_ult1    1.0         15

In [36]:
#create a dictionary to store each product a customer already has
used_recommendation_products = {}
target_cols_all = np.array(product_cols)
#iterate through used_products and add each one to used_recommendation_products
for idx,row_val in final_month.iterrows():
    used_recommendation_products.setdefault(row_val['ncodpers'],[]).append(target_cols_all[row_val['product_#']])
    if len(used_recommendation_products) % 100000 == 0:
        print(len(used_recommendation_products))

100000
200000
300000
300000
400000
500000
600000
600000
600000
600000
600000
600000


In [37]:
len(used_recommendation_products)

696539

In [38]:
#users are the customer codes for the testing data.

target_cols_all = np.array(product_cols)
final_preds = []
#iterate through our model's predictions (pred) and add the 7 most recommended products that the customer does not have.
for idx,predicted in enumerate(preds):
    ids = users[idx]
    top_product = target_cols_all[predicted]
    used_products = used_recommendation_products.get(ids,[])
    new_top_product = []
    for product in top_product:
        if product not in used_products:
            new_top_product.append(product)
        if len(new_top_product) == 7:
            break
    final_preds.append(' '.join(new_top_product))
    if len(final_preds) % 100000 == 0:
        print(len(final_preds))

100000
200000
300000
400000
500000
600000
700000
800000
900000


In [39]:
submission = pd.DataFrame({'ncodpers':users,'added_products':final_preds})
submission.to_csv('submission.csv',index=False)

In [40]:
print(datetime.datetime.now()-start_time)

0:57:14.488644


In [41]:
submission.head(10)

ncodpers                                     added_products
0     15889  ind_ctju_fin_ult1 ind_nom_pens_ult1 ind_ctma_f...
1   1170544  ind_recibo_ult1 ind_tjcr_fin_ult1 ind_nom_pens...
2   1170545  ind_tjcr_fin_ult1 ind_ctop_fin_ult1 ind_recibo...
3   1170547  ind_recibo_ult1 ind_ctma_fin_ult1 ind_nomina_u...
4   1170548  ind_ecue_fin_ult1 ind_recibo_ult1 ind_cno_fin_...
5   1170550  ind_recibo_ult1 ind_ecue_fin_ult1 ind_tjcr_fin...
6   1170552  ind_nom_pens_ult1 ind_nomina_ult1 ind_tjcr_fin...
7   1170553  ind_recibo_ult1 ind_ecue_fin_ult1 ind_nom_pens...
8   1170555  ind_recibo_ult1 ind_ecue_fin_ult1 ind_tjcr_fin...
9   1170557  ind_recibo_ult1 ind_ecue_fin_ult1 ind_nomina_u...

In [42]:
print(len(submission))
print(len(test))

929615
929615
